[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
rtt-target = { version = "0.5.0", path = "../../rtt-target/rtt-target" }
once_cell = { version = "1.19.0", default-features = false }
log = { version = "0.4.14", features = ["release_max_level_debug"] }
